version: '3'

services:
  server:
    build:
      context: ./docker/workspace
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    user: node
    tty: true
    volumes:
      - .:/home/node/work-management-backend
    ports:
      - ${APP_PORT}:3000
    working_dir: /home/node/work-management-backend
    command: ./docker/workspace/start-server.sh
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.8.3
    ports:
      - ${FORWARD_DB_PORT}:3306
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
